# basic options
title: Lesotho DHIS2 TB Docs
author: DHIS2/TB Team
pub_year: 2018
description: Information hub for TB Reports, Datasets, Indicators and Validation Rules
keywords: "tb, tuberculosis, lesotho, dhis2, ministry of health, egpaf, icap, "
github_username:  tbdocs

# add the full url for the github repository
repo: "https://github.com/tbdocs/2018"
url: https://tbdocs.github.io/2018

# Build settings
markdown: kramdown
theme: jekyll-theme-architect
